name: Test

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10.4
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements_full.txt

      - name: Install github annotations plugin
        run: pip install pytest-github-actions-annotate-failures

      - name: Run tests
        run: pytest