name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [ x64 ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.4
          architecture: ${{ matrix.architecture }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Set variables
        id: vars
        run: |
          echo "::set-output name=version::$(cat version.txt)"
          echo "::set-output name=sha_short::$(git rev-parse --short=7 ${{ github.sha }})"
      - name: Set architecture variables
        id: archvars
        run: |
          echo "::set-output name=bitness::$(python -c "import struct; print(struct.calcsize('P') * 8)")"
      - name: Build Windows App
        run: python -m PyInstaller --log-level=WARN main.spec
      - name: Bundle Windows App
        run: python build.py
      - name: Upload Windows App
        uses: actions/upload-artifact@v2
        with:
          name: wwrando-${{ steps.vars.outputs.version }}-${{ steps.vars.outputs.sha_short }}-windows-${{ steps.archvars.outputs.bitness }}bit
          path: dist/release_archive_${{ steps.vars.outputs.version }}_${{ steps.archvars.outputs.bitness }}bit/*